name: FaceLogin
main: Muqsit\FaceLogin
api: [2.0.0, 3.0.0, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
version: 1.0.0
author: Muqsit
permissions:
  facelogin.show:
    default: true
    description: Shows player their skin's face on joining.
